### ISSUE TITLE
Cannot detect variables

### ISSUE THREAD

**Issue by qst0** [JujuAdams/Chatterbox#1]
I'm always getting 
```
Chatterbox: WARNING! Local variable "c" doesn't exist
Chatterbox: WARNING! Local variable "c" doesn't exist
Chatterbox: WARNING! Local variable "d" doesn't exist
Chatterbox: WARNING! Internal variable "variable" doesn't exist
```
When trying to use variables or running Test.json in the oBeginnerExample

**Comment by JujuAdams** [comment]
Hiya, thanks for reporting this bug. I'm super busy right now but I'll look at this as soon as I am able.

**Comment by qst0** [comment]
Hey! Thanks @JujuAdams 🙏no rush.

**Comment by JujuAdams** [comment]
Hiya - Due to the release of a [new version](https://github.com/JujuAdams/Chatterbox/releases) that rewrites most of the codebase, I'm closing this issue as it likely no longer applies.

If this issue persists even in the newest version, please make a new ticket.
