### ISSUE TITLE
Do we want to support "format functions"?

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/Chatterbox#10]
Yarn has the ability to do many advanced, flexible things with dialogue, as shown by this test case: https://github.com/YarnSpinnerTool/YarnSpinner/blob/master/Tests/TestCases/FormatFunctions.yarn

This aids with localisation significantly but is an *enormous* amount of work.

**Comment by shdwcat** [comment]
I don't want this very strongly...

**Comment by JujuAdams** [comment]
Not feature of the v2 specification, and should be implemented using in-line expressions by calling a function
