### ISSUE TITLE
Crochet (visual editor) seems to be a dead project. Alternatives?

### ISSUE THREAD

**Issue by 825i** [JujuAdams/Chatterbox#106]
Hi, I'm new to this project and figuring out how to structure my story and dialogue in my own VN in GMS. So naturally I was recommended this by others who know about it.

After finding this project, the readme.md recommends checking out [Crochet](https://github.com/FaultyFunctions/Crochet) the visual editor. However, it looks pretty dead with no updates in 3 years and a few broken links now.

So the question is, what should I be using instead? I realise there's the web version here: https://faultyfunctions.github.io/Crochet/

However, I am wondering if it would be better off that I use something like YarnClassic: https://blurymind.github.io/YarnClassic/

This is purely a question and only based on speculation and what I've been able to gather in looking through the project myself. I'm looking to make an extremely story and dialogue heavy VN and it would be nice to structure that in a readable format, as well as have _some_ basic text effects for some of the dialogue for emphasis.

Thanks huge for any answers here.

**Comment by JujuAdams** [comment]
Does Crochet have issues that are preventing you from using it?
