### ISSUE TITLE
Making a branch option conditional

### ISSUE THREAD

**Issue by squiddonaut** [JujuAdams/Chatterbox#107]
Hello again :) is it possible to make a branch option only show when an if statement returns as true? For example, I would like to add an option in a branch that is only available to the player when a variable is >1. Is this possible natively in Chatterbox/Crochet? I fiddled around with trying different formats to achieve this effect but all of them were buggy or didn't display correctly. Thank you.

**Comment by JujuAdams** [comment]
Certainly is, see https://www.jujuadams.com/Chatterbox/#/latest/concept-yarn-script?id=options

You can check whether an option is available with `ChatterboxOptionConditionBool()` or set `CHATTERBOX_SHOW_REJECTED_OPTIONS` to `false`.

**Comment by squiddonaut** [comment]
Thank you! Followup question. I understand that `CHATTERBOX_SHOW_REJECTED_OPTIONS` is declared at the start of the game. However, I would like to be able to hide some rejected options and show other rejected options. Would it be possible to change all instances of this macro into a global variable that can be set to true or false within nodes? There's probably a more robust way of telling the game to ignore certain options, but that seems like the quick and dirty fix to me (as a total GM newb).

> Certainly is, see https://www.jujuadams.com/Chatterbox/#/latest/concept-yarn-script?id=options
> 
> You can check whether an option is available with `ChatterboxOptionConditionBool()` or set `CHATTERBOX_SHOW_REJECTED_OPTIONS` to `false`.

**Comment by JujuAdams** [comment]
That may work but I wouldn't advise it.

**Comment by squiddonaut** [comment]
Hmm… is there a native way to add a “tag” to a dialogue line in the way that you can tag a node, or would that need to be programmed separately?

**Comment by JujuAdams** [comment]
This is called "metadata": https://www.jujuadams.com/Chatterbox/#/latest/concept-metadata-and-speakers

This page is geared towards content and dialogue characters but you can use the same technique for options too.l.

**Comment by squiddonaut** [comment]
Thank you! I will look into this. :)
