### ISSUE TITLE
RandomOption creates empty lines in localization files

### ISSUE THREAD

**Issue by phablix** [JujuAdams/Chatterbox#108]
Not sure if it's intended or not but each random option seems to create an empty new line in localization files
![image](https://github.com/user-attachments/assets/eb2e0c15-afd6-47d2-934b-b181e37cbd89)

**Comment by JujuAdams** [comment]
I'll have a think about the best way to fix this ... hopefully nothing more than a check against empty strings.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Chatterbox/commit/755556c66b678cff7e7c776c29b7e65af6d2f355

Available in verson [2.15.1](https://github.com/JujuAdams/Chatterbox/releases/tag/2.15.1)
