### ISSUE TITLE
How do I make multiple lines?

### ISSUE THREAD

**Issue by aleriv-umich** [JujuAdams/Chatterbox#109]
I am using  [this tutorial](https://www.youtube.com/watch?v=r_hqY-7rT0c) and I wanna make it so a piece of the text can go over multiple lines if needed instead of putting everything on one line. Is there a way to do that?

**Comment by zeesworth** [comment]
you should be able to write `\n` in your line to place a line break at that position

**Comment by JujuAdams** [comment]
You can also turn off singleton mode and use `ChatterboxGetContent()` to obtain multiple lines of dialogue.
