### ISSUE TITLE
Strange IF-Statement Weirdness

### ISSUE THREAD

**Issue by OxyOxspring** [JujuAdams/Chatterbox#2]
It looks like a lot of yarn things have spaces between them.

**Comment by OxyOxspring** [comment]
In fact, now that I'm testing it, it doesn't seem to recognise if statements at all in game.

**Comment by OxyOxspring** [comment]
I'm trying to run the following Yarn:
`<<if CheckPlayerItem("Grave Dust" 100)>>
You have so much grave dust!
<<else>> 
Here you go! Enjoy. <<GivePlayerItem "Grave Dust" 100>>
<<end if>>
[[Thanks. | Start]]`
This results in:
`___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of  Step Event0
for object obj_Dialogue:

trying to index a variable which is not an array
 at gml_Script_chatterbox_select (line 421) -                                 _indent              = _instruction_array[ __CHATTERBOX_INSTRUCTION.INDENT ];
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_chatterbox_select (line 421)
called from - gml_Object_obj_Dialogue_Step_0 (line 26) - if (_select != undefined) chatterbox_select(chatterbox, _select);
`

**Comment by OxyOxspring** [comment]
Weirdly I'm getting more inconsistencies with the if-statements.

This is our new dialog system. It's very cool.

```
[[Where do I find out more about this?|FirstChoice]]
[[Sean, you're the best.|SecondaryChoice]]
[[I would like some Grave Dust, please. |GiveItem]]
[[Thanks, talk later. |Close]]
<<if CheckPlayerItem("Grave Dust" 100)>>
[[I've got a lot of Grave Dust|ExtraInfo]]
<<end if>>
<<if CheckPlayerItem("Grave Dust" 200)>>
[[I've got way too much Grave Dust|ExtraInfo]]
<<end if>>
```
Works fine... but if I do:

This is our new dialog system. It's very cool.

```
[[Where do I find out more about this?|FirstChoice]]
[[Sean, you're the best.|SecondaryChoice]]
[[I would like some Grave Dust, please. |GiveItem]]
<<if CheckPlayerItem("Grave Dust" 100)>>
[[I've got a lot of Grave Dust|ExtraInfo]]
<<end if>>
<<if CheckPlayerItem("Grave Dust" 200)>>
[[I've got way too much Grave Dust|ExtraInfo]]
<<end if>>
[[Thanks, talk later. |Close]]
```
Then "Thanks, talk later." will only appear when the other two if statements are true.

**Comment by JujuAdams** [comment]
Hiya - Due to the release of a [new version](https://github.com/JujuAdams/Chatterbox/releases) that rewrites most of the codebase, I'm closing this issue as it likely no longer applies.

If this issue persists even in the newest version, please make a new ticket.
