### ISSUE TITLE
if-statements blocks pause in a middle of option chains

### ISSUE THREAD

**Issue by Pumkin-dev** [JujuAdams/Chatterbox#29]
I've tried to make an if-statement block option but it seems that it blocks the proceeding of the option chains. Only in-line if-statements work
Examples:
in-line if-statement
`[[ What if I want to? |GoingToFight]] << if $testVariable is 0>> `
block if-statement
`<< if $testVariable is 0>>
    [[ What if I want to? |GoingToFight]]  
<< endif>>`
It would be great if chatterbox supports the two syntax!

**Comment by JujuAdams** [comment]
Thanks for the bug report, I'll take a look at this when I can,

**Comment by JujuAdams** [comment]
Unfortunately, the Yarn specification is quite strict about how if-statements interact with options/shortcuts so this feature cannot be supported. I'll pass on this feedback to the Yarn team and we'll see if they change their mind
