### ISSUE TITLE
Actions can't be used in shortcuts

### ISSUE THREAD

**Issue by mycelia** [JujuAdams/Chatterbox#3]
Say you have:
```
Chara: Starting the dialogue...
-> Shortcut 1
    Chara: Hello world <<action>>
    Chara: This shortcut has two lines.
->
Chara: Hello again world <<action>>
```

(with correct indentation ofc)

What you'll get is:
Chara: Starting the dialogue...
1. Shortcut 1
(press 1)
Chara: Hello world <<action>>
1. Shortcut 2
(press 1)
Chara: Hello again world <<action>>

In other words, the menu doesn't generate properly, and any extra lines under the shortcut are skipped, instead going straight to the next shortcut.

**Workaround:** just use nodes. Annoying but stable.

**Comment by JujuAdams** [comment]
Thanks for reporting this bug. Chatterbox isn't in active development at this time but I'll be sure to include this test case in future updates and releases.

**Comment by JujuAdams** [comment]
Hiya - Due to the release of a [new version](https://github.com/JujuAdams/Chatterbox/releases) that rewrites most of the codebase, I'm closing this issue as it likely no longer applies.

If this issue persists even in the newest version, please make a new ticket.
