### ISSUE TITLE
Add setting to have chatterbox pause/wait before loading options

### ISSUE THREAD

**Issue by FaultyFunctions** [JujuAdams/Chatterbox#36]
Currently in singleton mode if you have:

```
Sara: This is a first line.
Sara: This is a second line.
-> this is a shortcut
    [[JumpToNode]]
```

This gets translated via chatterbox (essentially) to:
```
Sara: This is a first line.
<<wait>>
Sara: This is a second line.
-> this is a shortcut
    [[JumpToNode]]
```

but an option to have it be:

```
Sara: This is a first line.
<<wait>>
Sara: This is a second line.
<<wait>>
-> this is a shortcut
    [[JumpToNode]]
```
would be really nice. Some styles of games don't display the options until after user input after the last piece of dialogue. This would just make chatterbox more flexible for people to use.

**Comment by JujuAdams** [comment]
Thank you for this suggestion!

Implemented on `dev`, will go into public release with 1.1.3
