### ISSUE TITLE
Feature request: Reset visited() function

### ISSUE THREAD

**Issue by mycelia** [JujuAdams/Chatterbox#52]
I want to let the player reset the game, but since I use visited() to mark what dialogue should play, various dialogue scenes don't play even after resetting. I can see a "variable map" where visited data is kept, but I'm kinda scared to mess with it on my own...

**Comment by JujuAdams** [comment]
Saw the discussion on Discord regarding this (https://discord.com/channels/724320164371497020/724320386816409690/881482919707824169), shall consider what options are available and add them to a release soon

**Comment by JujuAdams** [comment]
Implemented for v2.2.0 https://github.com/JujuAdams/Chatterbox/commit/7e1436576825d6ed692c7d4da0bac61208ab4de8
