### ISSUE TITLE
Feature request: Function to check if it's the first time visiting a node

### ISSUE THREAD

**Issue by docterhappey** [JujuAdams/Chatterbox#55]
This request is to be able to check if it's the first time visiting a Chatterbox node. Ideally, this is something that can also be reset (maybe with the future feature to reset `visited()`?). A potential name could be something like `<<firstVisited>>`

**Comment by JujuAdams** [comment]
Thank you for the feature request.

The `visited()` function, when called from inside a noce, will return exactly `1` when a node has been visited for the first time.

In version 2.2.0, the "visited" state for a node (in reality, a Chatterbox variable that gets set) can be reset by using either `ChatterboxVariableReset()` or `ChatterboxVariablesClearVisited()`.
