### ISSUE TITLE
A node will return visited as true even if this is the first time it is being visited

### ISSUE THREAD

**Issue by ThePounceThatWasPromised** [JujuAdams/Chatterbox#59]
In the yarn language tutorial the visited function is shown to mark a node as visited only if it was already visited once before, not if this current visit is your first visit, this is useful as it allows simply using the visited script to create a simple loop going back to the chatterbox's Start node without creating any additional logics.

In the chatterbox implementation the visited function marks visited on the first visit, so it's impossible to return false on visited if asking about current node. 

The fix is very simple but I'm very much a github noob so I don't know how to submit it, in the ChatterboxCreate script file inside the static jump function, the node is marked as visited at the end of the function after the current node has already been changed, moving mark visited to be before the new current node assignment (and wrapping it with an if(current_node) statement to make sure that current node actually exists which it wouldn't if this is the first jump) solves this and allows you to use the visited function the same way it is shown in the yarn tutorial.

And thank you for this awesome library (and for scribble) Juju, you are awesome :)

**Comment by JujuAdams** [comment]
This would be a breaking change for every current user so cannot be accepted until the next major version. There is unlikely to be a major version release for a long time.

The YarnScript2 specification does not include `visited()` so when developing this feature I had to guess what the Yarn developers intended. It took them almost 2 years to finish Yarn v2 (which includes the Unity implementation) and they treated my GameMaker port with extreme disinterest, so Chatterbox will not be an identical copy of whatever they decided to do.

`visited()` in Chatterbox returns the number of times a node has been visited (this isn't made explicit in the docs!). This is more flexible than a simple boolean. Checking `visited() == 1` will tell you if this is the first time a node has been visited therefore.
