### ISSUE TITLE
Error with custom actions using example from docs

### ISSUE THREAD

**Issue by nkennedy1027** [JujuAdams/Chatterbox#60]
When using the playMusic custom action example, I get the following error: 
```
Chatterbox:
Token (playMusic) is invalid: 
- Variables must be prefixed with a $ sign
- Strings must be delimited with " quote marks
```
I have the following node ('start') in a yarn file.  It's pulled from the chatterbox docs
```
Here's some text! 
<<playMusic>>
The music will have started now.
```
In GMS2 I have an object called **ob_convo_manager** with the following event scripts (truncated for clarity)
```
// ********************
// Create
// ********************
ChatterboxLoadFromFile("scripts/" + scriptName + ".yarn");
ChatterboxAddFunction("playMusic", play_background_music);
chatterbox = ChatterboxCreate(scriptName + ".yarn"); 

ChatterboxJump(chatterbox,"start");

// Get Content from Chatterbox
cbText = ChatterboxGetContent(chatterbox,0);
cbNodeTitle = ChatterboxGetCurrent(chatterbox);

// ********************
// Step
// ********************
with (targetBubble) {
        if (typist.get_state() == 1) {
	        ChatterboxContinue(ob_convo_manager.chatterbox);
        }
}
```
**play_background_music** is a script file that just has a show_debug_string call that logs "PLAY BACKGROUND MUSIC"

I'm using Scribble, so when my "Here's some text!" finishes printing (at typist.get_state() == 1 in "Step") and ChatterboxContinue fires, the error above occurs. 

Any suggestions you have would be amazing.

**Comment by JujuAdams** [comment]
What you've got [set for `CHATTERBOX_DIRECTION_MODE`](https://www.jujuadams.com/Chatterbox/#/latest/reference-configuration) controls how actions work. I'll update that error message to be more helpful since this behaviour is hidden away.
