### ISSUE TITLE
ChatterboxSourceNodeCount error

### ISSUE THREAD

**Issue by electronrancher** [JujuAdams/Chatterbox#66]
ChatterboxSourceNodeCount calls NodeCount but does not seem to pass _sourceName to NodeCount, resulting in error.

Function works if _sourceName is forced through to NodeCount

return global.chatterboxFiles[? _sourceName].NodeCount(_sourceName);

    static NodeCount = function(_sourceName)
    {
        return array_length(global.chatterboxFiles[? _sourceName].nodes);
    }

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Chatterbox/commit/1ebbad34c4c12fb1d37ecca55aabae8ce2c254d6
