### ISSUE TITLE
$variable names in function calls followed by a comma are parsed with the comma

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/Chatterbox#75]
[test - scribblebox.zip](https://github.com/JujuAdams/Chatterbox/files/9484032/test.-.scribblebox.zip)

When you call `<<ExampleFunction($a, $b)>>` Chatterbox thinks the first argument is named `a,` and bails when it can't find it.

It also won't parse argument `$b` but I don't know if that's a different bug or not.

If you add a variable with the name `a,` the lookup succeeds because Chatterbox now thinks the comma is part of the variable name, but it still won't parse the second argument (see the example).

If you call `<<ExampleFunction($a , $b)>>` from Chatterbox both arguments get parsed correctly but that's not really fixing the problem.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Chatterbox/commit/5281f7ed671cd20c6cc953e56c3c52fa9af70754
