### ISSUE TITLE
`ChatterboxGetContentSpeech` should split on the `:` after speaker data

### ISSUE THREAD

**Issue by Preskton** [JujuAdams/Chatterbox#92]
**Version:** https://github.com/JujuAdams/Chatterbox/releases/tag/2.10.4

## Steps to reproduce:

Load a conversation into Chatterbox like:
```
title: Repro
---
ActorA[mood:curious]: Who are you?
```

## Expected behavior

- `ChatterboxGetContentSpeaker` returns `ActorA`
- `ChatterboxGetContentSpeakerData` returns `mood:curious`
- `ChatterboxGetContentSpeech()` returns `Who are you?`

## Actual behavior

- 🟢 `ChatterboxGetContentSpeaker` returns `ActorA`
- 🟢  `ChatterboxGetContentSpeakerData` returns `mood:curious`
- 🔴 `ChatterboxGetContentSpeech()` returns `curious]: Who are you?`

## Notes

It looks like `ChatterboxGetContentSpeech` splits on the first `:` encountered, but it should take into account whether or not there is speaker data present.

**Workaround:** don't use `:` in speaker data.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Chatterbox/commit/b3ab820432daca3ab1fad474579afd5ccb737834
