### ISSUE TITLE
A way to see if an option was previously visited

### ISSUE THREAD

**Issue by tabularelf** [JujuAdams/Chatterbox#98]
Currently in Chatterbox, options have some very basic data that can be accessed from it. But there's no easy way of tracking options that have been visited at all. Requiring the developer to manually track each option. For cases like changing colour of previously visited options compared to options not visited yet, it ends up becoming a huge mess on the developers end since they end up having to track a variable per option.

**Comment by JujuAdams** [comment]
Not trivial because it's hard to robustly tracked visited state across sessions without uniquely identifying each option. I'd need to find a way to do that (probably via a meta tag).

**Comment by JujuAdams** [comment]
Decided to make it volatile i.e. not tracked between sessions.
